### ISSUE TITLE
how to get this to work

### ISSUE THREAD

**Issue by PandaWhoCodes** [mzmmoazam/Create-basic-Rest-API-using-Node.js-#1]
Kindly provide proper instructions on making this work. Installing node
and starting this app on the server
Screen shots would be great
Also proper formatting of code.

**Comment by mzmmoazam** [comment]
Sure , I will add them as soon as possible.
I will add another repo for that

**Comment by PandaWhoCodes** [comment]
dont do that
just add everything to your local every 
and push it as ann update 
Git stores different revisions

**Comment by mzmmoazam** [comment]
Ok ,  cool
